# Generated by Django 4.1.1 on 2022-09-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_commemnt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commemnt',
            new_name='Comment',
        ),
    ]
